### ISSUE TITLE
Turnos

### ISSUE THREAD

**Issue by Nidev-lab** [yanina-rodriguez-dev/veterinaria-frontend#57]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Saque un turno nuevo.

## Resultado esperado

• Al sacar un turno no poder elegir entre fechas pasadas.

## Resultado actual

• Puedo elegir cualquier fecha sin problema alguno.

## Posible solucion
 
• Poner un limitador a la hora de elegir las fechas para sacar turno.

## Captura

![image](https://github.com/yanina-rodriguez-dev/veterinaria-frontend/assets/53904695/bb684884-fb50-4b16-9ecf-390d0ab1fb8c)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas chicos! La verdad que el proyecto esta bien logrado, ademas de esto creo que no hay nada mas que corregir.

**Comment by yanina-rodriguez-dev** [comment]
Hola nico, muchisimas gracias! lo corregimos y te envio mail.

**Comment by yanina-rodriguez-dev** [comment]
Hola Nico! como estas ?
Ya pude solucionar lo de las fechas, que nos indicaste.
Esta bien que te lo avise por aca o debo mandar el mail de nuevo al correo
de rolling?
Es el proyecto de Huellitas Center.
Saludos!

**Comment by yanina-rodriguez-dev** [comment]
Solucionado! :D
